// Package cmd provides the generate command for code generation.
package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

var generateCmd = &cobra.Command{
	Use:     "generate [type] [name]",
	Aliases: []string{"gen", "g"},
	Short:   "Generate code scaffolds",
	Long: `Generate code scaffolds for various o9nn components.

Available generators:
  agent       Generate an agent scaffold
  tool        Generate a tool/function scaffold
  model       Generate a model wrapper scaffold
  plugin      Generate a plugin scaffold
  api         Generate API bindings from schema
  docs        Generate documentation templates

Examples:
  cogctl generate agent my-assistant
  cogctl generate tool calculator --language python
  cogctl generate model custom-llm --backend onnx
  cogctl generate plugin my-extension`,
	Args: cobra.MinimumNArgs(2),
	RunE: func(cmd *cobra.Command, args []string) error {
		genType := args[0]
		name := args[1]
		language, _ := cmd.Flags().GetString("language")
		outputDir, _ := cmd.Flags().GetString("output")
		force, _ := cmd.Flags().GetBool("force")

		return runGenerate(genType, name, language, outputDir, force)
	},
}

func runGenerate(genType, name, language, outputDir string, force bool) error {
	if outputDir == "" {
		outputDir = "."
	}

	fmt.Printf("Generating %s: %s\n", genType, name)
	fmt.Printf("  Language: %s\n", language)
	fmt.Printf("  Output:   %s\n", outputDir)
	fmt.Println()

	switch genType {
	case "agent":
		return generateAgent(name, language, outputDir, force)
	case "tool":
		return generateTool(name, language, outputDir, force)
	case "model":
		return generateModel(name, language, outputDir, force)
	case "plugin":
		return generatePlugin(name, language, outputDir, force)
	case "api":
		return generateAPI(name, language, outputDir, force)
	case "docs":
		return generateDocs(name, outputDir, force)
	default:
		return fmt.Errorf("unknown generator type: %s", genType)
	}
}

func generateAgent(name, language, outputDir string, force bool) error {
	var content string
	var filename string

	switch language {
	case "python", "py":
		filename = filepath.Join(outputDir, toSnakeCase(name)+".py")
		content = fmt.Sprintf(`"""
%s Agent

Generated by cogctl generate agent
"""

from o9nn_sdk import AgentBuilder, create_tool, create_sdk


class %sAgent:
    """Custom agent implementation."""
    
    def __init__(self, model: str = "llama-2-7b-chat"):
        self.sdk = create_sdk()
        self.model = model
        self.agent = None
    
    def setup(self):
        """Configure and build the agent."""
        # Define your tools
        search_tool = create_tool(
            name="search",
            description="Search for information",
            execute=self._search,
        )
        
        # Build the agent
        self.agent = (
            AgentBuilder("%s")
            .with_model({"name": self.model, "backend": "llama.cpp"})
            .with_system_prompt("You are a helpful assistant.")
            .add_tool(search_tool)
            .build()
        )
        
        return self
    
    def _search(self, query: str) -> str:
        """Search tool implementation."""
        # TODO: Implement search logic
        return f"Search results for: {query}"
    
    async def chat(self, message: str) -> str:
        """Send a message to the agent."""
        if self.agent is None:
            raise RuntimeError("Agent not initialized. Call setup() first.")
        
        response = await self.agent.chat(message)
        return response.content


def main():
    """Example usage."""
    agent = %sAgent().setup()
    # response = await agent.chat("Hello!")
    print(f"Agent {agent.model} ready")


if __name__ == "__main__":
    main()
`, name, toPascalCase(name), toKebabCase(name), toPascalCase(name))

	case "typescript", "ts":
		filename = filepath.Join(outputDir, toKebabCase(name)+".ts")
		content = fmt.Sprintf(`/**
 * %s Agent
 * 
 * Generated by cogctl generate agent
 */

import { createCogSDK, AgentBuilder, Tool } from '@o9nn/cog-sdk';

export interface %sAgentConfig {
  model?: string;
  systemPrompt?: string;
}

export class %sAgent {
  private sdk: ReturnType<typeof createCogSDK>;
  private model: string;
  private agent: any;

  constructor(config: %sAgentConfig = {}) {
    this.sdk = createCogSDK();
    this.model = config.model || 'llama-2-7b-chat';
  }

  /**
   * Configure and build the agent
   */
  async setup(): Promise<this> {
    // Define your tools
    const searchTool: Tool = {
      name: 'search',
      description: 'Search for information',
      parameters: {
        type: 'object',
        properties: {
          query: { type: 'string', description: 'Search query' },
        },
        required: ['query'],
      },
      execute: async (params) => this.search(params.query),
    };

    // Build the agent
    this.agent = await new AgentBuilder('%s')
      .withModel({ name: this.model, backend: 'llama.cpp' })
      .withSystemPrompt('You are a helpful assistant.')
      .addTool(searchTool)
      .build();

    return this;
  }

  /**
   * Search tool implementation
   */
  private async search(query: string): Promise<string> {
    // TODO: Implement search logic
    return ` + "`Search results for: ${query}`" + `;
  }

  /**
   * Send a message to the agent
   */
  async chat(message: string): Promise<string> {
    if (!this.agent) {
      throw new Error('Agent not initialized. Call setup() first.');
    }

    const response = await this.agent.chat(message);
    return response.content;
  }
}

// Example usage
async function main() {
  const agent = await new %sAgent().setup();
  console.log(` + "`Agent ${agent.model} ready`" + `);
}

main().catch(console.error);
`, name, toPascalCase(name), toPascalCase(name), toPascalCase(name), toKebabCase(name), toPascalCase(name))

	case "go":
		filename = filepath.Join(outputDir, toSnakeCase(name)+".go")
		content = fmt.Sprintf(`// Package agent provides the %s agent implementation.
//
// Generated by cogctl generate agent
package agent

import (
	"context"
	"fmt"

	cogsdk "github.com/o9nn/dro9nn/packages/sdk/go"
)

// %sAgent is a custom agent implementation.
type %sAgent struct {
	client *cogsdk.Client
	model  string
	agent  *cogsdk.AgentInfo
}

// %sAgentConfig holds agent configuration.
type %sAgentConfig struct {
	Model       string
	SystemPrompt string
}

// New%sAgent creates a new agent instance.
func New%sAgent(cfg *cogsdk.Config, agentCfg *%sAgentConfig) (*%sAgent, error) {
	client := cogsdk.NewClient(cfg)
	
	if agentCfg.Model == "" {
		agentCfg.Model = "llama-2-7b-chat"
	}

	return &%sAgent{
		client: client,
		model:  agentCfg.Model,
	}, nil
}

// Setup configures and creates the agent.
func (a *%sAgent) Setup(ctx context.Context) error {
	// Create the agent via API
	config := cogsdk.AgentConfig{
		Name:  "%s",
		Model: a.model,
	}

	agent, err := a.client.Agents().Create(ctx, config)
	if err != nil {
		return fmt.Errorf("failed to create agent: %%w", err)
	}

	a.agent = agent
	return nil
}

// Chat sends a message to the agent and returns the response.
func (a *%sAgent) Chat(ctx context.Context, message string) (string, error) {
	if a.agent == nil {
		return "", fmt.Errorf("agent not initialized, call Setup() first")
	}

	response, err := a.client.Agents().Send(ctx, a.agent.ID, message)
	if err != nil {
		return "", fmt.Errorf("chat failed: %%w", err)
	}

	return response.Message.Content, nil
}

// Close cleans up agent resources.
func (a *%sAgent) Close(ctx context.Context) error {
	if a.agent != nil {
		return a.client.Agents().Remove(ctx, a.agent.ID)
	}
	return nil
}
`, name, toPascalCase(name), toPascalCase(name), toPascalCase(name), toPascalCase(name),
			toPascalCase(name), toPascalCase(name), toPascalCase(name), toPascalCase(name),
			toPascalCase(name), toPascalCase(name), toKebabCase(name), toPascalCase(name), toPascalCase(name))

	default:
		return fmt.Errorf("unsupported language: %s", language)
	}

	return writeGeneratedFile(filename, content, force)
}

func generateTool(name, language, outputDir string, force bool) error {
	var content string
	var filename string

	switch language {
	case "python", "py":
		filename = filepath.Join(outputDir, "tools", toSnakeCase(name)+".py")
		content = fmt.Sprintf(`"""
%s Tool

Generated by cogctl generate tool
"""

from typing import Any
from o9nn_sdk import create_tool, ToolConfig


def %s_execute(params: dict[str, Any]) -> str:
    """
    Execute the %s tool.
    
    Args:
        params: Tool parameters
        
    Returns:
        Tool result as string
    """
    # TODO: Implement tool logic
    return f"Result from %s: {params}"


# Tool definition
%s_tool = create_tool(
    name="%s",
    description="Description of what this tool does",
    parameters={
        "type": "object",
        "properties": {
            "input": {
                "type": "string",
                "description": "Input parameter"
            }
        },
        "required": ["input"]
    },
    execute=%s_execute,
)


# Export for easy import
__all__ = ["%s_tool", "%s_execute"]
`, name, toSnakeCase(name), name, name, toSnakeCase(name), toSnakeCase(name), toSnakeCase(name), toSnakeCase(name), toSnakeCase(name))

	case "typescript", "ts":
		filename = filepath.Join(outputDir, "tools", toKebabCase(name)+".ts")
		content = fmt.Sprintf(`/**
 * %s Tool
 * 
 * Generated by cogctl generate tool
 */

import { Tool, ToolParameters } from '@o9nn/cog-sdk';

interface %sParams {
  input: string;
}

/**
 * Execute the %s tool
 */
async function execute(params: %sParams): Promise<string> {
  // TODO: Implement tool logic
  return ` + "`Result from %s: ${JSON.stringify(params)}`" + `;
}

/**
 * %s tool definition
 */
export const %sTool: Tool = {
  name: '%s',
  description: 'Description of what this tool does',
  parameters: {
    type: 'object',
    properties: {
      input: {
        type: 'string',
        description: 'Input parameter',
      },
    },
    required: ['input'],
  } as ToolParameters,
  execute,
};

export default %sTool;
`, name, toPascalCase(name), name, toPascalCase(name), name, name, toCamelCase(name), toKebabCase(name), toCamelCase(name))

	default:
		return fmt.Errorf("unsupported language: %s", language)
	}

	// Ensure directory exists
	if err := os.MkdirAll(filepath.Dir(filename), 0755); err != nil {
		return fmt.Errorf("failed to create directory: %w", err)
	}

	return writeGeneratedFile(filename, content, force)
}

func generateModel(name, language, outputDir string, force bool) error {
	filename := filepath.Join(outputDir, "models", toSnakeCase(name)+".py")
	content := fmt.Sprintf(`"""
%s Model Wrapper

Generated by cogctl generate model
"""

from typing import AsyncIterator
from o9nn_sdk import ModelConfig, InferenceOptions


class %sModel:
    """Custom model wrapper for %s."""
    
    def __init__(
        self,
        model_path: str,
        backend: str = "llama.cpp",
        context_length: int = 4096,
    ):
        self.model_path = model_path
        self.backend = backend
        self.context_length = context_length
        self._loaded = False
    
    async def load(self) -> None:
        """Load the model into memory."""
        # TODO: Implement model loading
        self._loaded = True
    
    async def unload(self) -> None:
        """Unload the model from memory."""
        # TODO: Implement model unloading
        self._loaded = False
    
    async def generate(
        self,
        prompt: str,
        max_tokens: int = 256,
        temperature: float = 0.7,
        **kwargs,
    ) -> str:
        """Generate text from prompt."""
        if not self._loaded:
            raise RuntimeError("Model not loaded. Call load() first.")
        
        # TODO: Implement generation
        return f"Generated response for: {prompt[:50]}..."
    
    async def generate_stream(
        self,
        prompt: str,
        max_tokens: int = 256,
        temperature: float = 0.7,
        **kwargs,
    ) -> AsyncIterator[str]:
        """Stream generated text."""
        if not self._loaded:
            raise RuntimeError("Model not loaded. Call load() first.")
        
        # TODO: Implement streaming generation
        response = await self.generate(prompt, max_tokens, temperature, **kwargs)
        for chunk in response.split():
            yield chunk + " "
    
    @property
    def is_loaded(self) -> bool:
        """Check if model is loaded."""
        return self._loaded
    
    def get_config(self) -> ModelConfig:
        """Get model configuration."""
        return ModelConfig(
            name="%s",
            path=self.model_path,
            backend=self.backend,
            context_length=self.context_length,
        )
`, name, toPascalCase(name), name, toKebabCase(name))

	// Ensure directory exists
	if err := os.MkdirAll(filepath.Dir(filename), 0755); err != nil {
		return fmt.Errorf("failed to create directory: %w", err)
	}

	return writeGeneratedFile(filename, content, force)
}

func generatePlugin(name, language, outputDir string, force bool) error {
	pluginDir := filepath.Join(outputDir, "plugins", toKebabCase(name))
	if err := os.MkdirAll(pluginDir, 0755); err != nil {
		return fmt.Errorf("failed to create plugin directory: %w", err)
	}

	// Create plugin manifest
	manifestFile := filepath.Join(pluginDir, "plugin.yaml")
	manifestContent := fmt.Sprintf(`# %s Plugin
# Generated by cogctl generate plugin

name: %s
version: 0.1.0
description: Description of the plugin
author: Your Name

# Plugin entry point
main: src/index.py

# Required capabilities
capabilities:
  - tools
  # - models
  # - agents

# Dependencies
dependencies:
  o9nn-sdk: ">=0.1.0"

# Plugin configuration schema
config:
  type: object
  properties:
    enabled:
      type: boolean
      default: true
    api_key:
      type: string
      description: API key for external service
`, name, toKebabCase(name))

	if err := writeGeneratedFile(manifestFile, manifestContent, force); err != nil {
		return err
	}

	// Create plugin source
	srcDir := filepath.Join(pluginDir, "src")
	if err := os.MkdirAll(srcDir, 0755); err != nil {
		return fmt.Errorf("failed to create src directory: %w", err)
	}

	srcFile := filepath.Join(srcDir, "index.py")
	srcContent := fmt.Sprintf(`"""
%s Plugin

Generated by cogctl generate plugin
"""

from typing import Any


class %sPlugin:
    """Main plugin class."""
    
    def __init__(self, config: dict[str, Any]):
        self.config = config
        self.enabled = config.get("enabled", True)
    
    async def initialize(self) -> None:
        """Initialize the plugin."""
        if not self.enabled:
            return
        
        # TODO: Implement initialization
        print(f"Initializing %s plugin...")
    
    async def shutdown(self) -> None:
        """Shutdown the plugin."""
        # TODO: Implement cleanup
        print(f"Shutting down %s plugin...")
    
    def register_tools(self) -> list:
        """Register tools provided by this plugin."""
        return [
            # Add your tools here
        ]
    
    def register_hooks(self) -> dict:
        """Register lifecycle hooks."""
        return {
            "before_inference": self.before_inference,
            "after_inference": self.after_inference,
        }
    
    async def before_inference(self, request: dict) -> dict:
        """Hook called before inference."""
        return request
    
    async def after_inference(self, response: dict) -> dict:
        """Hook called after inference."""
        return response


# Plugin factory function
def create_plugin(config: dict[str, Any]) -> %sPlugin:
    """Create plugin instance."""
    return %sPlugin(config)
`, name, toPascalCase(name), name, name, toPascalCase(name), toPascalCase(name))

	if err := writeGeneratedFile(srcFile, srcContent, force); err != nil {
		return err
	}

	// Create README
	readmeFile := filepath.Join(pluginDir, "README.md")
	readmeContent := fmt.Sprintf(`# %s Plugin

Description of the plugin.

## Installation

` + "```bash" + `
cogctl plugin install ./%s
` + "```" + `

## Configuration

` + "```yaml" + `
plugins:
  %s:
    enabled: true
` + "```" + `

## Usage

Describe how to use the plugin.

## Development

` + "```bash" + `
# Install dependencies
pip install -e .

# Run tests
pytest
` + "```" + `

## License

MIT
`, name, toKebabCase(name), toKebabCase(name))

	return writeGeneratedFile(readmeFile, readmeContent, force)
}

func generateAPI(name, language, outputDir string, force bool) error {
	fmt.Println("API binding generation requires a schema file.")
	fmt.Println("Usage: cogctl generate api <schema.yaml> --language <lang>")
	fmt.Println()
	fmt.Printf("Schema file: %s\n", name)
	fmt.Println()
	fmt.Println("This feature will generate client bindings from OpenAPI/AsyncAPI schemas.")
	return nil
}

func generateDocs(name, outputDir string, force bool) error {
	docsDir := filepath.Join(outputDir, "docs")
	if err := os.MkdirAll(docsDir, 0755); err != nil {
		return fmt.Errorf("failed to create docs directory: %w", err)
	}

	// Create index
	indexFile := filepath.Join(docsDir, "index.md")
	indexContent := fmt.Sprintf(`# %s Documentation

Welcome to the %s documentation.

## Getting Started

- [Installation](./installation.md)
- [Quick Start](./quickstart.md)
- [Configuration](./configuration.md)

## API Reference

- [Models](./api/models.md)
- [Agents](./api/agents.md)
- [Tools](./api/tools.md)

## Examples

- [Basic Usage](./examples/basic.md)
- [Advanced Patterns](./examples/advanced.md)

## Contributing

See [CONTRIBUTING.md](../CONTRIBUTING.md) for guidelines.
`, name, name)

	if err := writeGeneratedFile(indexFile, indexContent, force); err != nil {
		return err
	}

	fmt.Println("Generated documentation templates in", docsDir)
	return nil
}

func writeGeneratedFile(filename, content string, force bool) error {
	if !force {
		if _, err := os.Stat(filename); err == nil {
			return fmt.Errorf("file already exists: %s (use --force to overwrite)", filename)
		}
	}

	if err := os.WriteFile(filename, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write file: %w", err)
	}

	fmt.Printf("  Created: %s\n", filename)
	return nil
}

// String case conversion utilities

func toSnakeCase(s string) string {
	var result strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			result.WriteRune('_')
		}
		result.WriteRune(r)
	}
	return strings.ToLower(strings.ReplaceAll(result.String(), "-", "_"))
}

func toKebabCase(s string) string {
	return strings.ReplaceAll(toSnakeCase(s), "_", "-")
}

func toCamelCase(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-' || r == ' '
	})
	for i := 1; i < len(parts); i++ {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(string(parts[i][0])) + parts[i][1:]
		}
	}
	if len(parts) > 0 && len(parts[0]) > 0 {
		parts[0] = strings.ToLower(string(parts[0][0])) + parts[0][1:]
	}
	return strings.Join(parts, "")
}

func toPascalCase(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-' || r == ' '
	})
	for i := range parts {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(string(parts[i][0])) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

func init() {
	rootCmd.AddCommand(generateCmd)

	generateCmd.Flags().StringP("language", "l", "python", "target language (python, typescript, go)")
	generateCmd.Flags().StringP("output", "o", "", "output directory (default: current directory)")
	generateCmd.Flags().BoolP("force", "f", false, "overwrite existing files")
}
